# -*- coding: utf-8 -*-
"""food_waste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JouWxWlBVa_MWsX9Uvrrhj0Es9B1JxCo
"""

import pandas as pd
import numpy as np

train = pd.read_csv('/content/train.csv')



train.info()

train['staff_experience'] = train['staff_experience'].fillna(train['staff_experience'].mode()[0])

print(train.isnull().sum())

train.head(2)

train = train.drop(['special_event', 'ID','date'], axis=1)

print('Train columns after dropping: ', train.columns)

train.sample(2)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import numpy as np


X = train.drop('food_waste_kg', axis=1)
y = train['food_waste_kg']


preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), [6,7])

    ] , remainder='passthrough'
)


X_processed = preprocessor.fit_transform(X)
# Removed test_processed as evaluation will be on X_val

X_train, X_val, y_train, y_val = train_test_split(X_processed, y, test_size=0.2, random_state=42)


model = RandomForestRegressor(n_estimators=100, random_state=42)


model.fit(X_train, y_train)


y_pred_rf = model.predict(X_val) # Predict on the validation set

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np


mse_test = mean_squared_error(y_val, y_pred_rf) # Evaluate against y_val
rmse_test = np.sqrt(mse_test)
r2_test = r2_score(y_val, y_pred_rf) # Evaluate against y_val

print(f"Mean Squared Error (Validation): {mse_test:.4f}")
print(f"Root Mean Squared Error (Validation): {rmse_test:.4f}")
print(f"R-squared (Validation): {r2_test:.4f}")

from sklearn.ensemble import GradientBoostingRegressor


gb_model = GradientBoostingRegressor(n_estimators=100, random_state=42)

gb_model.fit(X_train, y_train)

y_pred_gb = gb_model.predict(X_val) # Predict on the validation set

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np


mse_gb = mean_squared_error(y_val, y_pred_gb) # Evaluate against y_val
rmse_gb = np.sqrt(mse_gb)
r2_gb = r2_score(y_val, y_pred_gb) # Evaluate against y_val

print(f"Gradient Boosting Mean Squared Error (Validation): {mse_gb:.4f}")
print(f"Gradient Boosting Root Mean Squared Error (Validation): {rmse_gb:.4f}")
print(f"Gradient Boosting R-squared (Validation): {r2_gb:.4f}")

"""### Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor


dt_model = DecisionTreeRegressor(random_state=42)


dt_model.fit(X_train, y_train)


y_pred_dt = dt_model.predict(X_val) # Predict on the validation set


mse_dt = mean_squared_error(y_val, y_pred_dt) # Evaluate against y_val
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_val, y_pred_dt) # Evaluate against y_val

print(f"Decision Tree Mean Squared Error (Validation): {mse_dt:.4f}")
print(f"Decision Tree Root Mean Squared Error (Validation): {rmse_dt:.4f}")
print(f"Decision Tree R-squared (Validation): {r2_dt:.4f}")

"""### Linear Regression"""

from sklearn.linear_model import LinearRegression


lr_model = LinearRegression()


lr_model.fit(X_train, y_train)


y_pred_lr = lr_model.predict(X_val) # Predict on the validation set


mse_lr = mean_squared_error(y_val, y_pred_lr) # Evaluate against y_val
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_val, y_pred_lr) # Evaluate against y_val

print(f"Linear Regression Mean Squared Error (Validation): {mse_lr:.4f}")
print(f"Linear Regression Root Mean Squared Error (Validation): {rmse_lr:.4f}")
print(f"Linear Regression R-squared (Validation): {r2_lr:.4f}")

"""### Neural Network (Multi-layer Perceptron Regressor)"""

from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val) # Scale the validation set


mlp_model = MLPRegressor(hidden_layer_sizes=(100,), activation='relu', solver='adam', max_iter=500, random_state=42)


mlp_model.fit(X_train_scaled, y_train)


y_pred_mlp = mlp_model.predict(X_val_scaled) # Predict on the scaled validation set


mse_mlp = mean_squared_error(y_val, y_pred_mlp) # Evaluate against y_val
rmse_mlp = np.sqrt(mse_mlp)
r2_mlp = r2_score(y_val, y_pred_mlp) # Evaluate against y_val

print(f"Neural Network (MLP) Mean Squared Error (Validation): {mse_mlp:.4f}")
print(f"Neural Network (MLP) Root Mean Squared Error (Validation): {rmse_mlp:.4f}")
print(f"Neural Network (MLP) R-squared (Validation): {r2_mlp:.4f}")

import pandas as pd


results = {
    'Model': ['Random Forest', 'Gradient Boosting', 'Decision Tree', 'Linear Regression', 'Neural Network (MLP)'],
    'MSE': [mse_test, mse_gb, mse_dt, mse_lr, mse_mlp],
    'RMSE': [rmse_test, rmse_gb, rmse_dt, rmse_lr, rmse_mlp],
    'R-squared': [r2_test, r2_gb, r2_dt, r2_lr, r2_mlp]
}


results_df = pd.DataFrame(results)


results_df = results_df.sort_values(by='R-squared', ascending=False)


display(results_df)

"""#### Visualizing Model Performance (R-squared)

This plot provides a visual comparison of the R-squared scores for all the models evaluated. A higher R-squared value indicates a better fit of the model to the data.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='R-squared', data=results_df, hue='Model', palette='viridis', legend=False)
plt.title('R-squared Comparison of Regression Models')
plt.xlabel('Regression Model')
plt.ylabel('R-squared Score')
plt.ylim(0, 1) # R-squared typically ranges from 0 to 1
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

